name: Issue management

on:
  issues:
    types: [assigned]
  pull_request:
    types: [opened, reopened]

# map fields with customized labels
env:
  todo: Todo
  assigned: Assigned
  done: Done

  PROJECTOWNER: 'rob-demo'
  PROJECTNUMBER: 2

permissions:
  issues: write
  repository-projects: write

jobs:
  issue-assigned:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'assigned' && github.repository == 'rob-demo/collaborate-effectively'
    steps:    
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ vars.GH_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
          
      - name: change-status-in-project
        env:
          GH_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          STATUSFIELDVALUE: "Todo"
          STATUSFIELDNAME: "Status"
          ISSUE_URL: "${{ github.event.issue.html_url }}"
          ISSUE_NUMBER: "${{ github.event.issue.number }}"
          ISSUE_ID: "${{ github.event.issue.id }}"
        shell: pwsh
        run: |
           $PROJECTOWNER = $env:PROJECTOWNER
           $PROJECTNUMBER = $env:PROJECTNUMBER
           $ISSUENUMBER = $env:ISSUE_NUMBER
           $ISSUEID = $env:ISSUE_ID
           $STATUSFIELDVALUE = $env:STATUSFIELDVALUE
           $STATUSFIELDNAME = $env:STATUSFIELDNAME
           
           echo "PROJECTOWNER = [$PROJECTOWNER] and PROJECTNUMBER = [$PROJECTNUMBER]"           
           $project = $(gh project list --owner "$PROJECTOWNER" --format json | ConvertFrom-Json).projects | Where-Object {$_.number -eq $PROJECTNUMBER}
           if ($null -eq $project) {
             Write-Error "Cannot locate project with owner [$PROJECTOWNER] and number [$PROJECTNUMBER]"
           }

           $issue = $(gh project item-list $PROJECTNUMBER --owner "$PROJECTOWNER" --format json | ConvertFrom-Json).items | Where-Object {$_.content.type -eq "issue" -And $_.content.number -eq $ISSUENUMBER}
           if ($null -eq $issue) {
             Write-Error "Cannot locate issue with number [$ISSUENUMBER] in project number [$PROJECTNUMBER] for owner [$PROJECTOWNER]"
           }
           
           # load the status field for this project
           $statusField = $(gh project field-list $PROJECTNUMBER --owner $PROJECTOWNER --format json | ConvertFrom-Json).fields | Where-Object {$_.name -eq "$STATUSFIELDNAME"}
           if ($statusField.type -eq "ProjectV2SingleSelectField") {
              # find the option with name
              $option = $statusField.options | Where-Object {$_.name -eq "$STATUSFIELDVALUE"}

              # todo: check if the status option is actually forward, to prevent us from going backward

              Write-Host "status fieldid: [$($statusField.id)] and ISSUE_ID = [$ISSUEID] and Issue.Id = [$($issue.id)]"
              gh project item-edit --project-id "$($project.id)" --id "$($issue.id)" --field-id "$($statusField.id)" --single-select-option-id "$($option.id)"
           }

           # todo: add support for other field types!

  test:
    runs-on: ubuntu-latest
    env:
      info: ${{ toJSON(github.event) }}
    steps:
      - run: |
           echo "Event: ${{ github.event_name }}"
           echo "Info: $info"

  pr-openend:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.repository == 'rob-demo/collaborate-effectively') && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:    
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ vars.GH_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
          
      - name: change-status-in-project
        env:
          GH_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          STATUSFIELDVALUE: "In progress"
          STATUSFIELDNAME: "Status"
          PULLREQUEST: "${{toJSON(github.event.pull_request)}}"
        shell: pwsh
        run: |
           $PROJECTOWNER = $env:PROJECTOWNER
           $PROJECTNUMBER = $env:PROJECTNUMBER
           $STATUSFIELDVALUE = $env:STATUSFIELDVALUE
           $STATUSFIELDNAME = $env:STATUSFIELDNAME
           $PULLREQUEST = $env:PULLREQUEST | ConvertFrom-Json           

           echo "PROJECTOWNER = [$PROJECTOWNER] and PROJECTNUMBER = [$PROJECTNUMBER]"           
           $project = $(gh project list --owner "$PROJECTOWNER" --format json | ConvertFrom-Json).projects | Where-Object {$_.number -eq $PROJECTNUMBER}
           if ($null -eq $project) {
             Write-Error "Cannot locate project with owner [$PROJECTOWNER] and number [$PROJECTNUMBER]"
           }

           # load all linked issues from PR
           $result = gh api graphql -f query=@'
             query {
               resource(url: "https://github.com/rob-demo/collaborate-effectively/pull/4") {
                 ... on PullRequest {
                 id
                 closingIssuesReferences (first: 50) {
                   edges {
                     node {
                       id
                       body
                       number
                       title
                     }
                   }
                 }
             }}}
             '@ | ConvertFrom-JSON

           if ($null -eq $result.data.resource.closingIssuesReferences.edges) {
             Write-Error "Error loading linked issues from this PR"
           }

           # load the status field for this project
           $statusField = $(gh project field-list $PROJECTNUMBER --owner $PROJECTOWNER --format json | ConvertFrom-Json).fields | Where-Object {$_.name -eq "$STATUSFIELDNAME"}
           if ($null -eq $statusField) {
             Write-Error "Cannot find status field with name [$STATUSFIELDNAME] for project [PROJECTNUMBER] in owner [$PROJECTOWNER]"
           }
            
           function updateIssueInProject {
             param (
               $PROJECTNUMBER,
               $PROJECTOWNER,
               $ISSUENUMBER,
               $statusField
             )

            $issue = $(gh project item-list $PROJECTNUMBER --owner "$PROJECTOWNER" --format json | ConvertFrom-Json).items | Where-Object {$_.content.type -eq "issue" -And $_.content.number -eq $ISSUENUMBER}
            if ($null -eq $issue) {
              Write-Error "Cannot locate issue with number [$ISSUENUMBER] in project number [$PROJECTNUMBER] for owner [$PROJECTOWNER]"
            }
            
            if ($statusField.type -eq "ProjectV2SingleSelectField") {
                # find the option with name
                $option = $statusField.options | Where-Object {$_.name -eq "$STATUSFIELDVALUE"}

                # todo: check if the status option is actually forward, to prevent us from going backward

                Write-Host "status fieldid: [$($statusField.id)] and ISSUE_ID = [$ISSUEID] and Issue.Id = [$($issue.id)]"
                gh project item-edit --project-id "$($project.id)" --id "$($issue.id)" --field-id "$($statusField.id)" --single-select-option-id "$($option.id)"
            }

            # todo: add support for other field types
           }

           foreach ($issue in $result.data.resource.closingIssuesReferences.edges) {
             updateIssueInProject -PROJECTNUMBER $PROJECTNUMBER --PROJECTOWNER $PROJECTOWNER -ISSUENUMBER $ISSUENUMBER -statusField $statusField -ISSUENUMBER "$($issue.number)"
           }

           