name: Issue management

on:
  issues:
    types: assigned

# map fields with customized labels
env:
  todo: Todo
  assigned: Assigned
  done: Done

  PROJECTOWNER: 'rob-demo'
  PROJECTNUMBER: 2
  ISSUE_URL: "${{ github.event.issue.html_url }}"
  ISSUE_NUMBER: "${{ github.event.issue.number }}"

permissions:
  issues: write
  repository-projects: write

jobs:
  issue-assigned:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'assigned' && github.repository == 'rob-demo/collaborate-effectively'    
    steps:    
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ vars.GH_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_PRIVATE_KEY }}
          
      - name: change-status-in-project
        env:
          GH_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        shell: pwsh
        run: |
           # test if the token works
           $PROJECTOWNER = $env:PROJECTOWNER
           $PROJECTNUMBER = $env:PROJECTNUMBER
           
           echo "PROJECTOWNER = [$PROJECTOWNER] and PROJECTNUMBER = [$PROJECTNUMBER]"
           gh project list --owner "$PROJECTOWNER"
           
           # load the status field for this project
           $statusField = $(gh project field-list 2 --owner $PROJECTOWNER --format json | ConvertFrom-Json).fields | Where-Object {$_.name -eq "Status"}

           Write-Host "status fieldid: [$($statusField.id)]"
                     
           gh project item-edit --project-id "$PROJECTNUMBER" --id "$env:ISSUE_NUMBER" --field-id "$($statusField.id)"  --text "Todo"
